defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: root

development:
  <<: *defaults
  database: medical_life_dev
  password:

test:
  <<: *defaults
  database: medical_life_test
  password:

production:
  <<: *defaults
  pool: 5
  database: medical_life_prod
  username: root
  password:
