# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b170ddc52d45660ece4633443ba3d5e5d04cb6615a6fae78ca051d803a568bc5a4b1493eed59eccbb7c5a577525e01e051f684d68d5a6e6db2df45bcafd1f70b

test:
  secret_key_base: bcb2fc8fd426779f574a2879b9a0e4b010985bb37e11eb4c385227b6ffb91e293dff08fb8ac26be41a0eafbe19cf4a2a6dd3dbbadf07db99890bc43cfada5256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 3b0018a020f42bd52f905ac67c9fc3e0b53f178fd54b51b09a22effd2616a5a16009619852795cd7dce3db87eb903dccd899b052d2ad73bf0fe1177ee304332
