puts "Loading specializations - start"
Specialization.create(description: "Acupuntura");
Specialization.create(description: "Alergia e Imunologia");
Specialization.create(description: "Anestesiologia");
Specialization.create(description: "Angiologia e Cirurgia vascular");
Specialization.create(description: "Oncologia");
Specialization.create(description: "Cardiologia");
Specialization.create(description: "Cirurgia cardiovascular");
Specialization.create(description: "Cirurgia da mão");
Specialization.create(description: "Cirurgia de cabeça e pescoço");
Specialization.create(description: "Cirurgia Geral");
Specialization.create(description: "Cirurgia do aparelho digestivo");
Specialization.create(description: "Cirurgia pediátrica");
Specialization.create(description: "Cirurgia plástica");
Specialization.create(description: "Cirurgia torácica");
Specialization.create(description: "Clínica médica");
Specialization.create(description: "Coloproctologia");
Specialization.create(description: "Dermatologia");
Specialization.create(description: "Endocrinologia");
Specialization.create(description: "Endoscopia");
Specialization.create(description: "Gastroenterologia");
Specialization.create(description: "Genética médica");
Specialization.create(description: "Geriatria");
Specialization.create(description: "Ginecologia e obstetrícia");
Specialization.create(description: "Hematologia e hemoterapia");
Specialization.create(description: "Homeopatia");
Specialization.create(description: "Infectologia");
Specialization.create(description: "Mastologia");
Specialization.create(description: "Medicina de família e comunidade");
Specialization.create(description: "Medicina do trabalho");
Specialization.create(description: "Medicina do tráfego");
Specialization.create(description: "Medicina esportiva");
Specialization.create(description: "Medicina física e reabilitação");
Specialization.create(description: "Medicina Intensiva");
Specialization.create(description: "Medicina legal");
Specialization.create(description: "Medicina nuclear");
Specialization.create(description: "Medicina preventiva e social");
Specialization.create(description: "Nefrologia");
Specialization.create(description: "Neurocirurgia");
Specialization.create(description: "Neurologia");
Specialization.create(description: "Nutrologia");
Specialization.create(description: "Oftalmologia");
Specialization.create(description: "Ortopedia e traumatologia");
Specialization.create(description: "Otorrinolaringologia");
Specialization.create(description: "Patologia");
Specialization.create(description: "Patologia Clínica/Medicina Laboratorial");
Specialization.create(description: "Pediatria");
Specialization.create(description: "Pneumologia");
Specialization.create(description: "Psiquiatria");
Specialization.create(description: "Radiologia e Diagnóstico por imagem");
Specialization.create(description: "Radioterapia");
Specialization.create(description: "Reumatologia");
Specialization.create(description: "Urologia");
puts "Loading specializations - end"
